#ifndef GAME_SERVER_CLASSES_H
#define GAME_SERVER_CLASSES_H

enum
{
	PLAYERCLASS_NONE = 0,
	
	START_HUMANCLASS,
	PLAYERCLASS_ASSASINS,
	PLAYERCLASS_BERSERK,
	PLAYERCLASS_HEALER,
	END_HUMANCLASS,
	
	NB_PLAYERCLASS,
	NB_HUMANCLASS = END_HUMANCLASS - START_HUMANCLASS - 1,
};

#endif
